# Generated by Django 4.1.6 on 2023-02-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_email_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_emails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='mail.email'),
        ),
    ]
