# Generated by Django 4.1.6 on 2023-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_user_user_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_emails',
        ),
        migrations.AddField(
            model_name='user',
            name='user_emails',
            field=models.ManyToManyField(related_name='users', to='mail.email'),
        ),
    ]
