# Generated by Django 4.1.6 on 2023-03-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_posts_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='following',
        ),
    ]
