# Generated by Django 4.1.6 on 2023-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reservations',
            field=models.ManyToManyField(to='reservation.reservation'),
        ),
    ]
