# Generated by Django 4.1.6 on 2023-02-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_user_user_emails_user_user_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_emails',
        ),
    ]
