# Generated by Django 4.1.6 on 2023-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='authors', to='network.post'),
        ),
    ]
