# Generated by Django 4.1.6 on 2023-03-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_user_posts_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
