# Generated by Django 4.1.6 on 2023-03-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_user_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='liked',
            new_name='liked_posts',
        ),
    ]
